// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"AltMenuScreen","status":true,"description":"Alternative menu screen layout.","parameters":{}},
{"name":"AltSaveScreen","status":true,"description":"Alternative save/load screen layout.","parameters":{}},
{"name":"ButtonPicture","status":true,"description":"Makes a picture clickable.","parameters":{}},
{"name":"TextPicture","status":true,"description":"Displays text as a picture.","parameters":{}},
{"name":"ScoreHUD","status":true,"description":"HUD Skor Sederhana - Menampilkan skor pemain di layar atas kiri (Variabel #1)","parameters":{}},
{"name":"CGMZ_Core","status":false,"description":"Core CGMZ Plugin, should be placed above all other CGMZ Plugins.","parameters":{"Check for Updates":"true","Dev Tools on Start":"false","Show FPS Counter":"false","Fullscreen":"false","Simulate Production Env":"false","Force Locale":"","Fallback Locale":"en-US","CGMZ Defaults":"","Scroll Speed":"1","Scroll Wait":"300","Scroll Deceleration":"0.92","Auto Scroll":"true","CGMZ Controls":"","Scroll Up":"w","Scroll Down":"s"}},
{"name":"CGMZ_TitleCommandWindow","status":false,"description":"Manage the menu command window","parameters":{"Visible Commands":"4","Columns":"1","Window Width":"30","Alignment":"center","Icon Alignment":"left","Keep Original Commands":"true","Commands":"[\"{\\\"Command Name\\\":\\\"Materi\\\",\\\"Icon\\\":\\\"15\\\",\\\"Command Symbol\\\":\\\"materi\\\",\\\"JS Command\\\":\\\"$gameTemp.reserveCommonEvent(15); SceneManager.push(Scene_Map);\\\\n\\\",\\\"Show JS\\\":\\\"return true;\\\",\\\"Enable JS\\\":\\\"return true;\\\",\\\"Background Image\\\":\\\"battlebacks1/Castle1\\\",\\\"Background Image X\\\":\\\"0\\\",\\\"Background Image Y\\\":\\\"0\\\",\\\"Selected Info\\\":\\\"\\\",\\\"Selected Text\\\":\\\"\\\",\\\"Selected Icon\\\":\\\"0\\\",\\\"Selected Back Img\\\":\\\"\\\",\\\"Selected Back Img X\\\":\\\"0\\\",\\\"Selected Back Img Y\\\":\\\"0\\\"}\"]","Integrations":"","Window Background":"","Window Settings":""}},
{"name":"ResizeCanvasMobile","status":true,"description":"Auto resize canvas for mobile landscape (no stretch)","parameters":{}},
{"name":"AutoMessageWrap","status":true,"description":"Auto-wraps dialogue text to fill full message window width.","parameters":{}}
];

